version: "3"
services:
  api:
    build:
      context: ./api
    image: api
    volumes:
      - ./api:/api:delegated
    depends_on:
      - postgres
    env_file:
      - .env
    command: ["yarn", "test:integration"]
  postgres:
    image: postgres:11.6
    ports:
      - "5432:5432"
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  # proxy:
  #   image: jwilder/nginx-proxy
  #   environment:
  #     - DEFAULT_HOST=synapse.codes
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - /var/run/docker.sock:/tmp/docker.sock:ro
  #     - ../synapse.codes.key:/etc/nginx/certs/synapse.codes.key:ro
  #     - ../synapse.codes.crt:/etc/nginx/certs/synapse.codes.crt:ro
  # frontend:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.frontend
  #   container_name: frontend
  #   image: "frontend"
  #   volumes:
  #     - ./frontend:/frontend
  #   # depends_on:
  #   #   - api
  #   environment:
  #     PORT: 3000
  #   command: ["yarn", "start"]
